version: "3.8"
services:
 mariadb:
    image: mariadb:10.7
    container_name: mariadb_glpi
    environment:
      - MYSQL_ROOT_PASSWORD=R00T#MhXw#T3zxfF
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=GLPI#MhXw#T3zxfF
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
